Add reusable components
clmnshn28/Aquencher1.0 pull request #8
Opened 2024-07-22 08:32 UTC by clmnshn28

- Created a 'components' folder to organize reusable components.

2024-07-22 14:01 UTC, otaKenneth commented on frontend/src/components/NewUserTextField.js
Why NewUserTextField, you can just name it TextField.

2024-07-22 14:02 UTC, otaKenneth commented on frontend/src/components/PasswordRequirements.js
You should put this with PasswordField component.

2024-07-22 14:03 UTC, otaKenneth commented on frontend/src/pages/admin/account/AccountSettingsAdmin.js
> +      <MainContent>
What happens to <slot/> component used in Routes?

2024-07-22 14:08 UTC, otaKenneth requested changes
Maximize the used of Routes/Slots components.

2024-07-23 01:33 UTC, clmnshn28 commented on frontend/src/components/NewUserTextField.js
okay po sir

2024-07-23 07:02 UTC, otaKenneth approved these changes

2024-07-23 07:02 UTC, merged